**Numpy-Task**

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__,np.show_config

('1.21.6', <function numpy.__config__.show>)

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
arr = np.array([500,20,120])  #1-D Array
print("The memory size of 1-D array:",arr.nbytes)

The memory size of 1-D array: 24


In [ ]:
arr = np.array([[200,300,150],[100,150,170]])
print("The memory size of 2-D array:",arr.nbytes)

The memory size of 2-D array: 48


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [127]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
arr = np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
arr = np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
arr = np.random.uniform(3,3,3)
print(arr)

[3. 3. 3.]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
arr = np.random.rand(10,10)
arr


In [ ]:
arr_max=np.max(arr)
arr_max

0.9987457235927536

In [ ]:
arr_min=np.min(arr)
arr_min

0.028983846286596227

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
arr = np.random.rand(30)
arr

array([0.22424023, 0.762246  , 0.10123608, 0.08860728, 0.93896326,
       0.05033164, 0.85731159, 0.20021912, 0.92335471, 0.89439321,
       0.733021  , 0.32918671, 0.66930148, 0.99962693, 0.53144711,
       0.16444761, 0.81073171, 0.88589979, 0.8001162 , 0.26187941,
       0.94047564, 0.97844194, 0.50943203, 0.5990304 , 0.20227403,
       0.31615528, 0.47718494, 0.5636523 , 0.09961738, 0.83946611])

In [ ]:
mean_arr=np.mean(arr)
mean_arr

0.5584097044364014

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\]

In [ ]:
arr_2d=np.ones((10,10))
arr_2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr_2d[1::-1,1::-1]=0
arr_2d

array([[0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
arr=np.ones((3,3))
print(arr)
arr_pad=np.pad(arr,pad_width=1,mode="constant",constant_values=0)
print(arr_pad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
arr_diag = np.diag(1+np.arange(4),k=-1)
arr_diag

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
arr_mat = np.zeros((8,8),dtype=int)
arr_mat

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
arr_mat[1::2,::2]=1
arr_mat[::2,1::2]=1
arr_mat

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
arr1=np.array([[0,1],[1,0]])
arr=np.tile(arr1,(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
arr = np.random.rand(5,5)
arr

array([[0.12981051, 0.0685533 , 0.45376148, 0.23317522, 0.8607931 ],
       [0.79174123, 0.86609637, 0.34297865, 0.52512926, 0.08587674],
       [0.77952059, 0.45103428, 0.33541101, 0.95318009, 0.03904343],
       [0.7746359 , 0.04569001, 0.52178337, 0.9182304 , 0.45349244],
       [0.47236183, 0.54036686, 0.91959756, 0.98978764, 0.41952177]])

In [ ]:
arr_min=np.min(arr)
arr_min
arr_max=np.max(arr)
arr_max

0.9897876364983458

In [ ]:
arr_x=((arr_min-arr)/(arr_max-arr_min))
arr_x

array([[-0.09546951, -0.03103871, -0.43620361, -0.20418929, -0.86432257],
       [-0.79169328, -0.86990058, -0.31968138, -0.51126878, -0.04925963],
       [-0.77883952, -0.43333512, -0.31172167, -0.96149591,  0.        ],
       [-0.77370176, -0.00699092, -0.50774954, -0.92473555, -0.43592062],
       [-0.45576759, -0.52729581, -0.92617354, -1.        , -0.40019002]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color_arr=np.dtype([("r",np.ubyte,1),
                    ("g",np.ubyte,1),
                    ("b",np.ubyte,1),
                    ("a",np.ubyte,1)])
color_arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
arr=np.dot(np.ones((5,3)),np.ones((3,2)))  #np.dot
print(arr)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
arr=np.ones((5,3)) @ np.ones((3,2))
print(arr)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
arr_1d=np.arange(9)
arr_1d[(3>arr_1d)&(8<=arr_1d)]*=-1
print(arr_1d)

[0 1 2 3 4 5 6 7 8]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

In [ ]:
print(sum(range(8),-1))
#from numpy import *
#print(sum(range(8),-1))

28


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [66]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [67]:
Z<Z>Z

array([False])

#### 28. What are the result of the following expressions?

In [ ]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
arr=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(arr)),arr))

[-5.  9. -7.  8.  8.  3. -2. -9. 10.  8.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
arr_1=np.random.randint(5,50,30)
arr_2=np.random.randint(5,50,30)
print(np.intersect1d(arr_1,arr_2))

[14 16 18 21 23 26 30 35 47]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
seterr=np.seterr(all="ignore")
arr=np.ones(1)/0
seterr_=np.seterr(**seterr)

In [ ]:
with np.errstate(divide="ignore"):
  arr=np.ones(1)/0

 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)
#No it is not True

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday=np.datetime64("today","D")-np.timedelta64(1,"D")
today=np.datetime64("today","D")
tomorrow=np.datetime64("today","D")+np.timedelta64(1,"D")
print("The Dates of yesterday:",yesterday)
print("The Dates of today:",today)
print("The Dates of tomorrow:",tomorrow)

The Dates of yesterday: 2022-07-21
The Dates of today: 2022-07-22
The Dates of tomorrow: 2022-07-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 

In [ ]:
july2016=np.arange("2016-07","2016-08",dtype="datetime64[D]")
july2016

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a=np.ones(5)*1
b=np.ones(5)*2
c=np.ones(5)*3
np.add(a,b,out=b)
np.negative(a,out=a)
np.multiply(a,b,out=a)
np.divide(a,2,out=a)

array([-1.5, -1.5, -1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
arr=np.random.uniform(0,20,20)
print(arr-arr%1)
print(np.floor(arr))
print(np.ceil(arr))
print(arr.astype(float))
print(np.trunc(arr))

[ 1.  6.  3.  7.  6. 14.  5.  3.  5.  6. 10. 13.  2.  1. 12. 16.  2.  3.
  4.  3.]
[ 1.  6.  3.  7.  6. 14.  5.  3.  5.  6. 10. 13.  2.  1. 12. 16.  2.  3.
  4.  3.]
[ 2.  7.  4.  8.  7. 15.  6.  4.  6.  7. 11. 14.  3.  2. 13. 17.  3.  4.
  5.  4.]
[ 1.23186547  6.92119581  3.46612521  7.60742389  6.62250096 14.88111677
  5.45835157  3.255334    5.56924646  6.17912774 10.38635031 13.17535592
  2.77213879  1.82268844 12.10785769 16.68844957  2.29495876  3.65006442
  4.19842137  3.85440022]
[ 1.  6.  3.  7.  6. 14.  5.  3.  5.  6. 10. 13.  2.  1. 12. 16.  2.  3.
  4.  3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
arr=np.zeros((5,5))
arr +=np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
  for i in range(10):
    yield i

arr=np.fromiter(generate(),dtype=float,count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
arr=np.linspace(0,2,22,endpoint=False)[1:]
print(arr)     

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091 1.         1.09090909
 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455 1.63636364
 1.72727273 1.81818182 1.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
arr=np.random.random(10)
arr.sort()
print(arr)

[0.06514628 0.16067847 0.28728902 0.45858603 0.6119154  0.72709853
 0.78269366 0.80077488 0.91067041 0.96507033]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
arr=np.arange(20)
print(np.add.reduce(arr))

190


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A=np.random.randint(0,3,7)
B=np.random.randint(0,3,7)
equal=np.allclose(A,B)
print(equal)
arr_equal=np.array_equal(A,B)
print(arr_equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [126]:
  arr=np.random.random(10)
  arr.flags.writeable=False
  arr

array([0.40687816, 0.55305824, 0.92259002, 0.90312257, 0.55493705,
       0.36224451, 0.21496389, 0.46641617, 0.07154407, 0.39950524])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
arr=np.random.random((20,2))
a,b=arr[:,0],arr[:,1]
x=np.sqrt(a**2+b**2)
y=np.arctan2(b,a)
print(x)
print(y)

[0.54369871 0.75458763 0.81311307 1.18381982 0.61705292 1.12549359
 0.12573046 0.91303413 0.11722952 0.46026034 0.62259534 0.44014312
 0.5510803  1.11116341 1.0112125  0.45798097 0.72311129 0.77227354
 0.98514374 0.46085876]
[0.24383426 1.56943185 1.44719232 0.6384548  1.16444927 0.7687522
 1.02323121 0.95453704 1.40215695 1.03815549 0.32713421 0.3659195
 0.28288959 0.69940808 0.73420593 1.0857113  0.5211435  1.54750151
 0.01492227 0.92382297]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [125]:
arr=np.random.random(10)
arr[arr.argmax()]=0
print(arr)

[0.         0.43646922 0.43923996 0.20049732 0.52754591 0.63757081
 0.29725615 0.34771786 0.70945309 0.52267253]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [124]:
arr=np.zeros((6,6),[('x',float),('y',float)])
arr['x'],arr['y']=np.meshgrid(np.linspace(0,2,6),
                              np.linspace(0,2,6))
print(arr)


[[(0. , 0. ) (0.4, 0. ) (0.8, 0. ) (1.2, 0. ) (1.6, 0. ) (2. , 0. )]
 [(0. , 0.4) (0.4, 0.4) (0.8, 0.4) (1.2, 0.4) (1.6, 0.4) (2. , 0.4)]
 [(0. , 0.8) (0.4, 0.8) (0.8, 0.8) (1.2, 0.8) (1.6, 0.8) (2. , 0.8)]
 [(0. , 1.2) (0.4, 1.2) (0.8, 1.2) (1.2, 1.2) (1.6, 1.2) (2. , 1.2)]
 [(0. , 1.6) (0.4, 1.6) (0.8, 1.6) (1.2, 1.6) (1.6, 1.6) (2. , 1.6)]
 [(0. , 2. ) (0.4, 2. ) (0.8, 2. ) (1.2, 2. ) (1.6, 2. ) (2. , 2. )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [123]:
x=np.arange(6)
y=x+0.5
c=1.0/np.subtract.outer(x,y)
print(np.linalg.det(c))

396.0368295558234


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [78]:
arr = np.zeros((4, 4))
np.set_printoptions
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
arr=np.arange(200)
x=np.random.uniform(0,100)
closestvalue=(np.abs(arr-x)).argmin()
print(arr[closestvalue])

66


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
arr=np.zeros(20,[('position',[('x',float,1),
                              ('y',float,1)]),
                 ('color', [('r',float,1),
                            ('g',float,1),
                            ('b',float,1)])])
print(arr)                              

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [121]:
arr=np.random.random((10,2))
a,b=np.atleast_2d(arr[:,0],arr[:,1])
c=np.sqrt( (a-a.T)**2 + (b-b.T)**2)
print(c)

[[0.         0.37664953 0.85472356 0.8346846  0.85537308 1.1054177
  0.86955379 0.93994817 0.87572954 0.62849959]
 [0.37664953 0.         0.66859808 0.50300739 0.68973327 0.73167197
  0.58347427 0.77405153 0.63330553 0.47213296]
 [0.85472356 0.66859808 0.         0.96932568 0.04818673 0.75326397
  0.2550897  0.10898669 1.20574666 0.22623674]
 [0.8346846  0.50300739 0.96932568 0.         1.00831372 0.52598914
  0.76144353 1.07570491 0.27520779 0.85433573]
 [0.85537308 0.68973327 0.04818673 1.00831372 0.         0.80132752
  0.30305138 0.0863546  1.24069497 0.23104793]
 [1.1054177  0.73167197 0.75326397 0.52598914 0.80132752 0.
  0.4983673  0.83287652 0.79438007 0.7716023 ]
 [0.86955379 0.58347427 0.2550897  0.76144353 0.30305138 0.4983673
  0.         0.34195308 1.01775363 0.32365334]
 [0.93994817 0.77405153 0.10898669 1.07570491 0.0863546  0.83287652
  0.34195308 0.         1.31422697 0.3173225 ]
 [0.87572954 0.63330553 1.20574666 0.27520779 1.24069497 0.79438007
  1.01775363 1.3142269

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
arr=np.arange(30, dtype=np.int32)
arr=arr.astype(np.float32, copy=False)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s=StringIO("""1,2,3,4,5\n
              6, , ,7,8\n
              , ,9,10,11\n""")
arr=np.genfromtxt(s, delimiter=",", dtype=np.int)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
arr=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(arr):
  print(index,value)
for index in np.ndindex(arr.shape):
  print(index,arr[index])  

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
a,b=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
c=np.sqrt(a*a+b*b)
sigma, mu =1.0,0.0
x=np.exp(-((c-mu)**2/(2.0*sigma**2)))
print(x)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [79]:
a=10
b=3
arr=np.zeros((a,a))
np.put(arr,np.random.choice(range(a*a),b,replace=False),1)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x=np.random.rand(5,10)
y=x- x.mean(axis=1, keepdims=True)
y=x- x.mean(axis=1).reshape(-1,1)
print(y)

[[-0.08565126  0.38488336 -0.54232657  0.2478013  -0.36744292  0.27055873
   0.12417616 -0.21864664 -0.01423713  0.20088498]
 [ 0.08250692 -0.06541965  0.22662469  0.09363374 -0.27583506  0.40519477
   0.29007122 -0.31815728 -0.26918807 -0.16943128]
 [-0.16864222  0.36563405  0.17024908  0.1868571  -0.26593853  0.01871336
  -0.34281201  0.09928496 -0.1588422   0.09549641]
 [ 0.31597422 -0.14985563 -0.39556537  0.35580895  0.51254766 -0.45141468
   0.17081167  0.02298606 -0.45460175  0.07330888]
 [-0.23336292 -0.12975974 -0.14751228  0.24036046  0.07782168  0.32367328
   0.19149691  0.13915597 -0.32194004 -0.1399333 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
arr=np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[3 2 8]
 [8 5 5]
 [3 9 3]]
[[3 2 8]
 [8 5 5]
 [3 9 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
arr=np.random.randint(0,3,(3,10))
print((~arr.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
arr=np.random.uniform(0,2,20)
x=0.5
y=arr.flat[np.abs(arr-x).argmin()]
print(y)

0.4665374397974871


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
a=np.arange(5).reshape(5,1)
b=np.arange(5).reshape(1,5)
iter=np.nditer([a,b,None])
for x,y,z in iter: z[...]=x+y
print(iter.operands[2])

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [80]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
#for np.bincount
z=np.ones(10)
i=np.random.randint(0,len(z),20)
z+=np.bincount(i,minlength=len(x))
print(z)
#for np.add.at
np.add.at(x,y,1)
print(x)

[6. 5. 2. 1. 1. 3. 4. 5. 1. 2.]
[7. 3. 3. 9. 7. 7. 5. 3. 5. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [119]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [118]:
w,h= 16,16
s=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
m=s[...,0]*256*256+s[...,1]*256+s[...,2]
n=len(np.unique(m))
print(np.unique(s))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
x=np.random.randint(0,10,(3,4,3,4))
sum=x.sum(axis=(-2,-1))
print(sum)
#To get sum over the last two axis at once
sum=x.reshape(x.shape[:-2]+(-1,)).sum(axis=-1)
print(sum)

[[74 65 58 50]
 [63 37 61 55]
 [54 54 39 68]]
[[74 65 58 50]
 [63 37 61 55]
 [54 54 39 68]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
a=np.random.uniform(0,1,100)
b=np.random.randint(0,10,100)
a_sums=np.bincount(b,weights=a)
a_counts=np.bincount(b)
a_means=a_sums/a_counts
print(a_means)

[0.27614382 0.55134332 0.45536962 0.54034654 0.67737181 0.51029008
 0.46758819 0.47397514 0.56039311 0.6441557 ]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
x = np.random.uniform(0,1,(5,5))
y = np.random.uniform(0,1,(5,5))
 
np.diag(np.dot(x, y))
np.sum(x * y.T, axis=1)
np.einsum("ij,ji->i", x, y)

array([1.14567526, 0.78060551, 1.35245975, 1.07334105, 1.5899851 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
arr = np.array([1,2,3,4,5])
nz = 3
arr0 = np.zeros(len(arr) + (len(arr)-1)*(nz))
arr0[::nz+1] = arr
print(arr0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
print(x * y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
arr = np.arange(25).reshape(5,5)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 27) ( 1, 53) ( 3, 64) ( 3, 66) (10, 76) (10, 95) (14, 19) (14, 81)
 (16, 83) (16, 86) (19, 81) (21, 71) (21, 79) (27, 53) (46, 50) (46, 86)
 (46, 94) (46, 95) (50, 94) (53, 73) (53, 76) (54, 97) (54, 99) (64, 66)
 (71, 79) (73, 76) (76, 95) (83, 86) (86, 95) (97, 99)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
x = np.bincount([1,1,2,3,4,4,6])
y = np.repeat(np.arange(len(x)), x)
print(y)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
arr = rolling(np.arange(10), 3)
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
arr = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

arr1 = np.random.uniform(-1.0,1.0,100)
np.negative(arr1, out=arr1)

array([-0.23826762, -0.71446488, -0.02370112,  0.97617431, -0.79141141,
       -0.73552671,  0.43627008, -0.63738243, -0.10573582, -0.16866504,
        0.56003591,  0.00803482, -0.794213  , -0.27569005, -0.30120514,
       -0.49623104,  0.0346476 , -0.604144  , -0.19242748,  0.69435396,
        0.12695222,  0.232453  ,  0.29441859, -0.81171493, -0.86036294,
        0.21797189, -0.94013605,  0.90077268,  0.71259761,  0.22480358,
       -0.65209226,  0.4798936 , -0.8542606 , -0.14089088,  0.39505119,
       -0.16971346,  0.79824834, -0.17132396,  0.70124418,  0.13838993,
        0.7468445 ,  0.76135278, -0.97712707,  0.03808648, -0.71041701,
        0.96254498, -0.03582593, -0.36004687,  0.04788864,  0.05939018,
        0.01269207,  0.31501984, -0.54805449,  0.97272917, -0.62343315,
        0.51729342,  0.45111813,  0.36853733,  0.01288284, -0.36330715,
       -0.86288809, -0.86877165, -0.34140685, -0.23896774,  0.48303582,
        0.29490737, -0.36123517, -0.05031145,  0.5211969 ,  0.93

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[13.31457178  0.06955658  6.7893682  10.20543579  1.30435735  8.01245465
  7.85808824 11.10460763  4.80715555 15.72664719]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.55797671  8.93918002  7.52362578 13.69455865  5.7281512  12.54032834
  12.27042966 11.23088342  2.89573609 13.47938125]
 [ 9.10929863  3.20372957 12.85910085  5.75863226  5.86886449 18.51845357
   0.90046221 15.3099244  10.08443376  0.73709996]
 [10.7781952   6.34174923 11.94320421  9.58929349  2.1503545  17.33985319
   4.00519395 14.89758091  5.51637097  5.71724729]
 [ 3.96089409  1.46947608  3.70400689  6.1074289   4.74307023  9.07976977
   7.48300764  6.76331786  0.38952011  7.58920463]
 [ 4.50842144  7.93968697  1.471629    3.35667412  3.97982881  4.34025486
   1.87088598  0.8049363   4.06703531  0.53181759]
 [ 9.66590155 14.31777642  3.64598017 10.11248223  1.71343339  2.52073651
   3.46525867  2.02245058  8.24710781  5.57825142]
 [ 0.66478373  4.22401923  1.71325485  0.08946422  2.78521337  7.40355494
   2.77679138  4.19419355  4.057955    2.18445429]
 [ 8.09551404  3.54449687 10.02770424  6.87188724  1.88318759 15.53728352
   2.76950612 12.78396679  6.1330441   3.99377164]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [116]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 3 1 5 6 8 6 4 1 1]
 [5 5 8 2 3 2 6 0 2 2]
 [3 9 5 2 5 1 3 4 1 8]
 [7 9 8 2 9 1 7 1 9 2]
 [7 9 5 7 9 1 3 5 2 5]
 [6 9 1 4 7 8 7 9 2 7]
 [4 2 9 3 2 9 4 6 3 3]
 [1 1 9 6 7 3 6 2 6 2]
 [8 2 8 5 8 4 3 7 5 6]
 [2 8 8 2 3 9 9 3 3 8]]
[[0 0 0 0 0]
 [0 4 3 1 5]
 [0 5 5 8 2]
 [0 3 9 5 2]
 [0 7 9 8 2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
x = np.arange(1,15,dtype=np.uint32)
y = stride_tricks.as_strided(x,(11,4),(4,4))
print(y)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [117]:
x = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(x) 
rank_matrix = np.sum(S > 1e-10)
print(rank_matrix)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
arr = np.random.randint(0,20,60)
print(np.bincount(arr).argmax())

16


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
arr = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
C = stride_tricks.as_strided(arr, shape=(i, j, n, n), strides=arr.strides + arr.strides)
print(C)

[[[[2 1 0]
   [4 2 1]
   [4 0 0]]

  [[1 0 0]
   [2 1 2]
   [0 0 0]]

  [[0 0 2]
   [1 2 2]
   [0 0 3]]

  [[0 2 0]
   [2 2 2]
   [0 3 4]]

  [[2 0 3]
   [2 2 3]
   [3 4 3]]

  [[0 3 0]
   [2 3 1]
   [4 3 1]]

  [[3 0 1]
   [3 1 0]
   [3 1 1]]

  [[0 1 1]
   [1 0 4]
   [1 1 4]]]


 [[[4 2 1]
   [4 0 0]
   [4 4 1]]

  [[2 1 2]
   [0 0 0]
   [4 1 0]]

  [[1 2 2]
   [0 0 3]
   [1 0 3]]

  [[2 2 2]
   [0 3 4]
   [0 3 0]]

  [[2 2 3]
   [3 4 3]
   [3 0 2]]

  [[2 3 1]
   [4 3 1]
   [0 2 4]]

  [[3 1 0]
   [3 1 1]
   [2 4 3]]

  [[1 0 4]
   [1 1 4]
   [4 3 2]]]


 [[[4 0 0]
   [4 4 1]
   [1 4 4]]

  [[0 0 0]
   [4 1 0]
   [4 4 3]]

  [[0 0 3]
   [1 0 3]
   [4 3 4]]

  [[0 3 4]
   [0 3 0]
   [3 4 1]]

  [[3 4 3]
   [3 0 2]
   [4 1 0]]

  [[4 3 1]
   [0 2 4]
   [1 0 0]]

  [[3 1 1]
   [2 4 3]
   [0 0 1]]

  [[1 1 4]
   [4 3 2]
   [0 1 1]]]


 [[[4 4 1]
   [1 4 4]
   [4 0 3]]

  [[4 1 0]
   [4 4 3]
   [0 3 1]]

  [[1 0 3]
   [4 3 4]
   [3 1 1]]

  [[0 3 0]
   [3 4 1]
   [1 1 1]]

  [[3 0 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4 10 10  8  9]
 [10  2  8 15  7]
 [10  8  7 42  8]
 [ 8 15 42  9 10]
 [ 9  7  8 10  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [115]:


p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)



[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
x = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
                                       np.arange(0, x.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [104]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [105]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5
print (arr[np.argsort(arr)[-n:]])

print (arr[np.argpartition(-arr,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9998 9995 9999 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [106]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [107]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [108]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.73 s per loop
10 loops, best of 5: 135 ms per loop
10 loops, best of 5: 134 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [109]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [110]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 4 0]
 [1 4 1]
 [1 1 3]
 [2 0 3]
 [3 4 1]
 [0 3 3]
 [3 3 1]
 [0 4 0]
 [4 2 0]
 [3 0 2]]
[[2 4 0]
 [1 4 1]
 [1 1 3]
 [2 0 3]
 [3 4 1]
 [0 3 3]
 [3 3 1]
 [0 4 0]
 [4 2 0]
 [3 0 2]]
[[2 4 0]
 [1 4 1]
 [1 1 3]
 [2 0 3]
 [3 4 1]
 [0 3 3]
 [3 3 1]
 [0 4 0]
 [4 2 0]
 [3 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [111]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [112]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [113]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.43222278, 0.44943076, 0.44285259, 0.24042558, 0.13780151,
        0.09085013, 0.57368595, 0.12944999, 0.35411162, 0.38417174],
       [0.67049511, 0.69718936, 0.68698483, 0.37296547, 0.21376763,
        0.14093327, 0.88994296, 0.20081215, 0.54932345, 0.59595488],
       [0.52932723, 0.5504012 , 0.54234516, 0.2944403 , 0.16876041,
        0.11126079, 0.70257193, 0.15853261, 0.43366739, 0.47048091],
       [0.66517922, 0.69166183, 0.68153821, 0.37000849, 0.21207282,
        0.13981591, 0.88288723, 0.19922005, 0.54496825, 0.59122997],
       [0.29537476, 0.30713444, 0.30263902, 0.16430334, 0.09417155,
        0.06208566, 0.39204863, 0.08846424, 0.24199473, 0.26253738],
       [0.25151045, 0.26152378, 0.25769594, 0.13990365, 0.08018671,
        0.0528657 , 0.33382788, 0.07532695, 0.20605757, 0.22354955],
       [0.02821157, 0.02933475, 0.02890538, 0.01569279, 0.00899443,
        0.00592987, 0.03744499, 0.00844932, 0.02311318, 0.02507523],
       [0.64846777, 0.67428506, 0.6644157

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [114]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)
print(x,y)

[  0.           0.09950042   0.19601332   0.28660095   0.3684244
   0.43879128   0.49520137   0.53538953   0.55736537   0.55944897
   0.54030231   0.49895573   0.43482931   0.34774848   0.237954
   0.1061058   -0.04671924  -0.21903564  -0.40896377  -0.61425018
  -0.83229367  -1.06017682  -1.29470246  -1.53243485  -1.76974492
  -2.00285904  -2.22791076  -2.44099478  -2.63822255  -2.81577868
  -2.96997749  -3.09731897  -3.19454328  -3.25868324  -3.28711385
  -3.27759841  -3.2283303   -3.13797012  -3.00567731  -2.83113599
  -2.61457448  -2.35677818  -2.05909545  -1.72343644  -1.35226463
  -0.9485811   -0.51590162  -0.05822672   0.41999512   0.91391061
   1.41831093   1.92768649   2.43628669   2.93818398   3.42734153
   3.89768376   4.34316892   4.75786287   5.1360132    5.47212274
   5.76102172   5.99793747   6.178561     6.29910941   6.35638348
   6.34781957   6.27153511   6.12636709   5.91190293   5.62850319
   5.27731578   4.86028133   4.38012946   3.84036588   3.24525022
   2.59976488

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [101]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [102]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.18129539  0.18499137]
